### ISSUE TITLE
Question about rule parsing

### ISSUE THREAD

**Issue by mathieuancelinserli** [CleverCloud/biscuit-java#24]
I just have a question about the rule parser : 

why is there a `substring(1)` when parsing a rule ? (https://github.com/CleverCloud/biscuit-java/blob/master/src/main/java/com/clevercloud/biscuit/token/builder/parser/Parser.java#L28). I saw in the parser tests that the parsed rule is starting with a `*` (https://github.com/CleverCloud/biscuit-java/blob/master/src/test/java/com/clevercloud/biscuit/builder/parser/ParserTest.java#L69). Is it a mandatory thing ? I don't see anything about it in the biscuit spec.

Thanks for your answers !

**Comment by Geal** [comment]
in an older version of the syntax, rules started with a `*`, it is not the case anymore with the current version of the specification. See https://github.com/CleverCloud/biscuit-java/tree/1.0 for the current work on 1.0

**Comment by mathieuancelinserli** [comment]
Nice :) 

I didn't noticed the 1.0 branch before.

Do you have an ETA for the 1.0 version ? (no pressure, just want to know if I can hold a bit or go with the 0.6.1 for now)

**Comment by Geal** [comment]
the 1.0 version is only missing an updated parser, which should happen within a week or two (no definite deadline though). The rest of the library already handles 1.0 tokens properly and supports all of the new features. So you should go with 1.0 if you can live without the parser for now. Otherwise, tokens generated with the current published version will be usable with 1.0 too, no worries

**Comment by mathieuancelinserli** [comment]
Ok, as I'm not releasing that soon, maybe I'll have the 1.0 :) 

I'm closing the issue

Thanks @Geal
